// Some words for random search of songs
const words = ["The Beatles","Queen","Deep Purple","Meshuggah","Megadeth","Marilyn Manson","Manowar","Machine Head","Lordi","Linkin Park","Limp Bizkit","Led Zeppelin","Lamb of God","Lacuna Coil","Korn","KISS","Killswitch Engage","Judas Priest","Jimi Hendrix","Janes Addiction","Iron Maiden","Guns N Roses","Godsmack","Genesis","Evanescence","DragonForce","Down","Dokken","Disturbed","Dio","Deftones","Def Leppard","Cradle Of Filth","Bon Jovi","Black Sabbath","Black Label Society","Avenged Sevenfold","Audioslave","A Perfect Circle","Anthrax","Alice In Chains","Alice Cooper ","Aerosmith","AC/DC","Accept","ZZ Top","Whitesnake","WASP","Van Halen","Type O Negative","Twisted Sister","Tool","The Who","The Darkness","The Cult","System Of A Down","Stone Temple Pilots","Stone Sour","Staind","Slipknot","Slayer","Skid Row","Sevendust","Scorpions","Saliva","Rush","Rolling Stones","Red Hot Chili Peppers","Rammstein","Rage Against The Machine","Quiet Riot","Queensryche","Poison","P O D","Pink Floyd","Pearl Jam","Pantera","Nirvana","Nine Inch Nails","Mushroomhead","Murderdolls","Mudvayne","Motley Crue","Motorhead","Metallica","Europe","Eminem","Kanye West","Beastie Boys","2Pac","JAY-Z","Snoop Dogg","Cypress Hill","50 Cent","Dr. Dre","Nas","Black Eyed Peas","OutKast","Wu-Tang Clan","The Roots","Lil' Wayne","Public Enemy","Fort Minor","Ice Cube","Ludacris","T.I.","The Game","A Tribe Called Quest","DMX","The Notorious B.I.G.","Common","Busta Rhymes","Mos Def","Run-D.M.C.","N.W.A","The Streets","Missy Elliott","O.S.T.R.","Xzibit","Timbaland","Lupe Fiasco","Kid Cudi","Gang Starr","D12","De La Soul","Nelly","Fugees","Hollywood Undead","Noize MC","Mobb Deep","Akon","N*E*R*D","Talib Kweli","Method Man","Nicki Minaj","Drake","Flo Rida","Atmosphere","Jurassic 5","MF DOOM","Jedi Mind Tricks","Immortal Technique","Will Smith","Die Antwoord","Jay-Z and Linkin Park","Paktofonika","Gym Class Heroes","Dizzee Rascal","Aesop Rock", "Daft Punk","The Prodigy","Depeche Mode","Massive Attack","Björk","Moby","Radiohead","The Chemical Brothers","Air","Gorillaz","Röyksopp","Aphex Twin","Portishead","MGMT","Crystal Castles","Boards of Canada","Kraftwerk","Fatboy Slim","Goldfrapp","The Knife","Nine Inch Nails", "Justice","M83","Lady Gaga","New Order","Pendulum","The Postal Service","Ladytron","Amon Tobin","Faithless","LCD Soundsystem","Bonobo","UNKLE","The xx","Thievery Corporation","DJ Shadow","Moloko","Autechre","Zero 7","M.I.A.","Hot Chip","Underworld"];
// Screen Position Table
const posit = 
    [
    //    left       center        right
        [0, 0.05], [0.3, 0.05], [0.6, 0.05], // up
        [0, 0.4], [0.3, 0.4], [0.6, 0.4],    // center
        [0, 0.8], [0.3, 0.8], [0.6, 0.8]     // down
    ];
